### ISSUE TITLE
CriticalTime not providing correct values, ProcessingTime not working

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Metrics.PerformanceCounters#11]
CriticalTime is getting values that only accumulate over time, are always x1000 times what they used to be and never drop to 0.
ProcessingTime isn't working at all.

**Comment by dvdstelt** [comment]
I'm already working on a fix that involves Metrics & PerfCounters.

**Comment by dvdstelt** [comment]
It took me a while before I figured out my performance counters were corrupt. Had to download Windows 10 iso to replace some files again.

**Comment by dvdstelt** [comment]
@danielmarbach I didn't do anything with the update interval just yet. Wanted to create a different PR for it and discuss separately, so we can fix the current version.

**Comment by danielmarbach** [comment]
Makes sense
