### ISSUE TITLE
Don't use NumberOfItems32

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Metrics.PerformanceCounters#13]
<sup>*Moved from https://github.com/Particular/NServiceBus.Metrics/issues/30 opened by @ramonsmits on [11 May 2017 11:55 UTC](https://github.com/Particular/NServiceBus.Metrics/issues/30)*</sup>
In https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/64 it was raised that currently NumberOfItems32 is used. This can give an incorrect average representation over time as the 'last writer wins'. This metric could be improved by using RateOfCountsPerSecond32 as that is based on averages.

**Comment by dvdstelt** [comment]
<sup>*@dvdstelt commented on <a id="issuecomment-305798223" href="13#user-content-issuecomment-305798223">02 Jun 2017 14:07 UTC</a>*</sup>
Wrong repo, @ramonsmits 
If you don't pay attention to the correct repo, how can others pay attention to a single issue inside the monitoring repo ;-)

**Comment by dvdstelt** [comment]
I propose we add two additional perfcounters that report in ms and are the correct PerformanceCounter type.

**Comment by ramonsmits** [comment]
As we have already released this I think that is the only right thing to do @dvdstelt

**Comment by Scooletz** [comment]
Will be addressed by #20

**Comment by Scooletz** [comment]
#20 is merged
