### ISSUE TITLE
Counter data index order might need to be backward compatible, new counters might need to be appended at the end

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Metrics.PerformanceCounters#22]
The current version has a different counter data index order than previous versions. This might break compatibility. Documentation is not really clear about this but I think this must be researched.

**Comment by Scooletz** [comment]
Every time we install counters we recreate the category. Getting performance counters by index as described in this [SO answer](https://stackoverflow.com/questions/33804402/get-performancecounter-by-index) and this [Microsoft KB](https://support.microsoft.com/en-us/help/287159/using-pdh-apis-correctly-in-a-localized-language) is done when "querying performance counters" and the index is not written in stone. I see no problem with our current scripting.

@Particular/metrics-maintainers feel free to chime in.

**Comment by ramonsmits** [comment]
@Scooletz Thanks for that KB link it mentions:

> Therefore, the index value for performance extension counter providers such as Microsoft Internet Information Server, and Microsoft SQL Server, will be different from system to system, depending on installation sequence.

Is that what you mean with your comment "the index is not written in stone."?

**Comment by Scooletz** [comment]
Not only this but also the probability of having them assigned differently, when rerunning the installer. Accessing by index is used purely for cross-language support, to query first for the index, then to query for all the counters by the index (not by localized name).

Does it address your remark? If yes, feel free to close it.

**Comment by ramonsmits** [comment]
@Scooletz Learned today that the value needs to be reported in `Stopwatch.Frequency` and not in milliseconds.

In a call with him we looked at how the value is reported in the windows performance counters and it is in **seconds** with a fraction:

![image](https://user-images.githubusercontent.com/152998/28575136-50264ab2-7150-11e7-966e-746eb4270767.png)

He clarified the API usage which was correct so this can be closed.

**Comment by Scooletz** [comment]
@ramonsmits This is the issue not for the frequency but order of performance counters creation data. I think you might have wanted to close #21 ? I'm reopening it for now.

**Comment by Scooletz** [comment]
I think that I mistook this with other issue on my own :)

**Comment by ramonsmits** [comment]
Reinstalling the new counters results in a corrupted perfmon view.

![image](https://user-images.githubusercontent.com/152998/28618366-71058496-7204-11e7-8e71-10baac147752.png)


I think this is related to the index order. @tmasternak has a similar issue which was resolved after a restart of this box. I didn't restarted yet and get a similar experience.

Reopening this as this needs to be verified.

**Comment by ramonsmits** [comment]
Verified this together with @Scooletz . We made 3 revisions of a test application that preserved the counter order:

1. Number
2. Number + Duration
3. Number + Duration + Rate

We create the counters for revision 1, then ran the process to update the counters and checked perfmon. While v1 was still running, we ran v2 which recreated the counters. THis resulted in the v1 process to disconnect with the perfmon. The new counter was visible in the perfmon 'add counterse' dialog but after adding, the new counter was not showing any value.

We then did the same for v3 and had the exact same experience. 

We restarted *Windows Management Instrumention* but this didn't make perfmon work again. We needed to restart the machine to make the newly added performance counters work in perfmon.


## Conclusion

A machine restart always seems to be required when recreating **and extending** the counters to make the newly added counters work.

Preserving the counter order when recreating a category:

- does not ensure running processes that are using existing counters to continue reporting, they get disconnected
- does not make newly created counters immediately available in perfmon, this required a restart
- prevents existing counters to show corrupted values after restarting the endpoint processes.
