### ISSUE TITLE
Performance counter creation script always deletes `nservicebus` category

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Metrics.PerformanceCounters#25]
Connects to https://github.com/Particular/PlatformDevelopment/issues/1332

## Problem
Performance counter creation script ([cs]() and [ps1]()) deletes `nservicebus` category as the first step of execution. 

This is problematic as deleting/creating `nservicebus` category will impact all running endpoints instances on a machine and will result in the windows performance counter connection to fail for the current running `Perfmon` views. On the other hand, once created, category cannot be modified (no counters can be added or removed).

## Solution
In order to delete `nservicebus` category only when needed creation script should work according to the following rules:
- If `nservicebus` category does not exist, then create the category and the known counter definitions (new installation),
- If `nservicebus` category exists, but does not contain all known counter definitions, delete the category and re-create it with all known counter definitions (update),
- Otherwise leave `nservicebus` category as is.

## Plan of Attack
- [x] Provide expected `.ps1` script
- [x] Provide expected `.cs` script
- [x] Change generators
- [x] Fix on `develop` [PR](https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/pull/27)
- [x] Release `1.1.2` patch version [PR](https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/pull/37)

**Comment by ramonsmits** [comment]
@tmasternak as discussed

**Comment by Scooletz** [comment]
Ping @tmasternak I'm closing it's been released.
