### ISSUE TITLE
Enable by default

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Metrics.PerformanceCounters#26]
If this package is already explicitly added to the project, why should you still need to explicitly enable it? There are no arguments needed to enable the package

**Comment by tmasternak** [comment]
For me explicit enabling reduces the `works by magic` factor.

**Comment by andreasohlund** [comment]
Given the restrictions in assembly scanning on netcore we're moving towards always requiring explicit enabling to ensure that the assembly is always loaded into the appdomain (https://github.com/Particular/DotNetCoreLaunch/issues/90)

👍 to be explicit

**Comment by Scooletz** [comment]
Being given two comments above, I'm closing it.
