### ISSUE TITLE
Enabling the plugin would blow up on send only endpoints

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Metrics.PerformanceCounters#40]
Since v7 no longer provides addresses (logical and physical) for send only endpoints since they by definition don't have an address this line will blow up

https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/develop/src/NServiceBus.Metrics.PerformanceCounters/PerformanceCountersFeature.cs#L19

It seems like perfcounters isn't applicable to send only endpoints so perhaps check and throw "new Exception("Perfcounters are not applicable to send only endpoints");" or similar?

**Comment by Scooletz** [comment]
Thx @andreasohlund I followed the trace you provided. Let me describe the current state of the `Metrics.*` first

In Metrics 3.0 we've got a check on startup that does throws in the hosting endpoints is `send-only`

https://github.com/Particular/NServiceBus.Metrics/blob/develop/src/NServiceBus.Metrics/MetricsFeature.cs#L11

Also, we enable metrics, as we need this feature to get performance counters running

https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/develop/src/NServiceBus.Metrics.PerformanceCounters/PerformanceCountersFeature.cs#L11-L14

My reasoning is following:
- we enable `Metrics` and depend on them in this package
- we don't know if metrics are

**Comment by andreasohlund** [comment]
> we should check and throw if this is send only (we can use Metrics approach)

Sounds good to me

**Comment by Scooletz** [comment]
@Particular/metrics-maintainers pls chime in

**Comment by seanfarmar** [comment]
@Scooletz Sounds good to me

**Comment by Scooletz** [comment]
Solved by #50
