### ISSUE TITLE
Obsolete performance counters script generators

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.Metrics.PerformanceCounters#46]
## Overview
Currently we generate performance counters based on internal scanning of `NSB.Metrics` package. This does not align well with current `Probes` abstraction as:
 * Single probe can be aggregated to more than one performance counter 
 * It's hard to come-up with generic way to generate counter description based on probe description.

**Comment by Scooletz** [comment]
Although this issue removes a lot of "msbuild magic" that is currently used for generating script, it's not a must-have for 2.0 and can be easily addressed later.

**Comment by DavidBoike** [comment]
This was implemented in https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/pull/68 as part of an enhancement release and will be released soon as 4.0.
